### ISSUE TITLE
A question about how to choose args.dip_type

### ISSUE THREAD

**Issue by xiongchuanchao** [gistvision/DIP-denosing#1]
["dip_sure", "eSURE", "NCV_y", "eSURE_fixed", 'eSURE_new', 'eSURE_alpha', "eSURE_uniform", "eSURE_clip","eSURE_real", "no_div", "PURE", "PURE_dc", "dip_sure_new"],which one should be chosen when I adopt  'Oursw/o STE ' or 'Our' method.

**Comment by dustlrdk** [comment]
If you want to get 'Ours', please use the following scripts. 
  python main.py --dip_type eSURE_uniform --net_type s2s --exp_tag CSet9 --optim RAdam --force_steplr --desc sigma25 denoising --sigma 25

For 'Ours w/o STE', you can make it by modifying the loss function; the code in loss.py from L45 to L52.
It makes a new noise instance for each iteration. Make it fixed after the 1st iteration.

Actually, 'Ours w/o STE' is eSURE_fixed but the code is deprecated.
